### ISSUE TITLE
Do not specify Yarn as a dependency if not strictly needed

### ISSUE THREAD

**Issue by ademarco** [yhuard/ecl-example#3]
### Scope
As core team we will limit frontend work to the minimum, trying to leverage the work done on the component libraries. Since we can do everything that we do with Yarn with NPM we were wondering if we could remove Yarn and related code from the boilerplate project.

### Tasks
- [x] Remove Yarn and related code
- [x] Update README

**Comment by yhuard** [comment]
Known bug: https://github.com/yarnpkg/yarn/issues/2172

I'll remove yarn dependency. Thanks for your report!

**Comment by yhuard** [comment]
I kept yarn as it's safer (provides more predictable results) but also added the npm equivalents.
